# Generated by Django 4.2.4 on 2023-08-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField(max_length=500)),
                ('post_time', models.DateField(auto_now_add=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boards.board')),
            ],
        ),
    ]
