# Generated by Django 4.2.4 on 2023-08-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
