# Generated by Django 4.2.4 on 2023-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
